const TAWK='https://embed.tawk.to/6ab059ace9134d343e1acadb/1k30dsj8l';
const games={
'blox-fruits':{name:'Blox Fruits',img:'images/blox-fruits.jpg',desc:'Frutas, maestrias, contas e serviços para evoluir.',buy:[['Fruta Blox (Qualquer)',3],['Fruta Lendária',12],['Fruta Mítica',25],['Fruta Especial',45],['Maestria 1–100',10],['Maestria 100–300',30],['Maestria 300–600',55],['Maestria 600–999',90],['Conta Starter',15],['Conta Full',70],['Conta com 2 Frutas',120],['Conta God',250]],sell:[['Fruta Comum',1],['Fruta Rara',5],['Fruta Lendária',15],['Fruta Mítica',30],['Maestria',2],['Conta Starter',10],['Conta Full',40],['Conta com Frutas',80]],kit:['Kit Contas + Frutas','R$ 120']},
'roube-ovo':{name:'Roube um Ovo',img:'images/roube-um-ovo.jpg',desc:'Pets e velocidade para deixar sua conta mais avançada.',buy:[['Pet de 100M',8],['Pet de 1B',25],['Pet de 5B',60],['Pet de 10B',100],['Kit 5 Pets',45],['Kit 10 Pets',85],['+100 Níveis',10],['+1.000 Níveis',45]],sell:[['Pet 100M',4],['Pet 1B',15],['Pet 5B',35],['Pet 10B',60],['Conta com Pets',50]],kit:['Kit 20B','R$ 300']},
'brainrot':{name:'Roube um Brainrot',img:'images/brainrot.jpg',desc:'Brainrots por valor e kits completos.',buy:[['Brainrot 100M',8],['Brainrot 1B',25],['Brainrot 5B',60],['Brainrot 10B',100],['Kit 5 Brainrots',45],['Kit 10 Brainrots',85]],sell:[['Brainrot 100M',4],['Brainrot 1B',15],['Brainrot 5B',35],['Brainrot 10B',60],['Conta com Brainrots',50]],kit:['Kit Completo','R$ 180']},
'99-noites':{name:'99 Noites na Floresta',img:'images/99-noites.jpg',desc:'Progresso por tempo de farm.',buy:[['10 minutos',2],['20 minutos',4],['30 minutos',6],['1 hora',11],['1h 10m',13],['1h 30m',17],['Kit 1h + bônus',15]],sell:[['Conta com progresso',10],['Conta avançada',25]],kit:['Kit 6h + Bônus','R$ 70']},
'speed':{name:'+1 Speed Keyboard Escape',img:'images/speed.jpg',desc:'Níveis e progresso de velocidade.',buy:[['+100 Níveis',10],['+500 Níveis',30],['+1.000 Níveis',50],['+5.000 Níveis',80],['+10.000 Níveis',100],['Kit Nível + Speed',120]],sell:[['Conta com níveis',30],['Conta avançada',70]],kit:['Kit 20K + Wins + Rebirth','R$ 250']},
'murder':{name:'Murder Mystery 2',img:'images/murder.jpg',desc:'Níveis, prestígios, armas e itens.',buy:[['+100 Níveis',8],['+500 Níveis',25],['+1.000 Níveis',40],['+5 Prestígios',30],['+10 Prestígios',55],['Arma comum',10],['Arma rara',25],['Kit Prestígio + Armas',80]],sell:[['Conta com níveis',20],['Conta com prestígios',45],['Conta com armas',60]],kit:['Kit 10 Prestígios','R$ 350']},
'rivals':{name:'RIVALS',img:'images/rivals.jpg',desc:'Armas, skins, níveis e extras.',buy:[['Arma comum',8],['Arma rara',20],['Arma lendária',40],['Skin de arma',15],['+100 Níveis',10],['+500 Níveis',30],['Kit Armas + Níveis',70]],sell:[['Conta com armas',30],['Conta completa',80],['Skin/Item',10]],kit:['Kit 1K + Extras','R$ 300']},
'assassinos':{name:'Assassinos 2',img:'images/assassinos.jpg',desc:'Níveis, armas, itens e contas.',buy:[['+100 Níveis',8],['+500 Níveis',25],['Arma comum',8],['Arma rara',20],['Arma lendária',35],['Kit Níveis + Armas',60]],sell:[['Conta com níveis',25],['Conta com armas',45],['Conta completa',70]],kit:['Kit 1K + Extras','R$ 300']}
};
const order=Object.keys(games);
function money(n){return 'R$ '+Number(n).toFixed(2).replace('.',',')}
function sellMoney(n){return money(n/2.65)}
function toggleMenu(){document.querySelector('nav')?.classList.toggle('open')}
function openSupport(){if(window.Tawk_API&&typeof Tawk_API.maximize==='function'){Tawk_API.maximize();return}window.open('suporte.html','_self')}
function gameCard(k){const g=games[k];return `<a class="game-card" href="precos.html?jogo=${k}"><div class="game-image"><img src="${g.img}" alt="${g.name}"><span>FARM</span></div><div class="game-info"><strong>${g.name}</strong><small>${g.desc}</small><b>Ver opções →</b></div></a>`}
function kitCard(k){const g=games[k];return `<a class="kit-card" href="precos.html?jogo=${k}"><img src="${g.img}" alt="${g.name}"><span>KIT</span><strong>${g.name}</strong><small>${g.kit[0]}</small><b>${g.kit[1]}</b></a>`}
function renderLists(){const gp=document.getElementById('gamesPage');if(gp)gp.innerHTML=order.map(gameCard).join('');const hg=document.getElementById('homeGames');if(hg)hg.innerHTML=order.map(gameCard).join('');const hk=document.getElementById('homeKits');if(hk)hk.innerHTML=order.map(kitCard).join('');const ak=document.getElementById('allKits');if(ak)ak.innerHTML=order.map(kitCard).join('')}
function renderGame(){const el=document.getElementById('gameDetails');if(!el)return;const key=new URLSearchParams(location.search).get('jogo')||'blox-fruits';const g=games[key]||games['blox-fruits'];document.title=g.name+' — Blox BTN';const buy=g.buy.map(x=>`<article class="product"><b>${x[0]}</b><strong>${money(x[1])}</strong><button onclick="openSupport()">Comprar</button></article>`).join('');const sell=g.sell.map(x=>`<article class="product sell-product"><b>${x[0]}</b><strong>${sellMoney(x[1])}</strong><button onclick="openSupport()">Vender</button></article>`).join('');el.innerHTML=`<section class="game-hero" style="--bg:url('${g.img}')"><div><span class="badge">FARM</span><h1>${g.name}</h1><p>${g.desc}</p></div></section><div class="price-title"><span class="eyebrow">OPÇÕES</span><h2>O que você precisa?</h2><p>Escolha uma opção e fale com o suporte para combinar o pedido.</p></div><section class="buy-sell"><div class="shop"><h2>🛒 COMPRAR</h2><div class="products">${buy}</div></div><div class="shop sell"><h2>↗ VENDER</h2><p class="negotiation">Os valores de venda estão divididos por 2,65. Você pode negociar pelo Tawk.to.</p><div class="products">${sell}</div></div></section><section class="game-kit"><div><span class="eyebrow">KIT DO JOGO</span><h2>🎁 ${g.kit[0]}</h2><p>Kit especial deste jogo.</p></div><strong>${g.kit[1]}</strong><button class="btn primary" onclick="openSupport()">Negociar no Tawk.to</button></section>`}
renderLists();renderGame();
(function loadTawk(){window.Tawk_API=window.Tawk_API||{};window.Tawk_LoadStart=new Date();const s=document.createElement('script');s.async=true;s.src=TAWK;s.charset='UTF-8';s.setAttribute('crossorigin','*');document.body.appendChild(s)})();
